### ISSUE TITLE
Does not work for me in 10.11.1

### ISSUE THREAD

**Issue by mityukov** [dhoulb/subl#12]
Chrome asks to use app handler -- this part works. Then Mac Os X asks if I'm really sure to open a 3rd-party app. I click Open, then nothing happens. I have Sublime Text 2 installed @ `/Applications/Sublime Text 2.app`. The URL I'm trying to open looks like this:

subl://open?url=file:///Users/username/version-control/symfony/hello_world/src/AppBundle/Controller/DefaultController.php&line=157

Honestly, I have no idea how to get more details.. If I launch it in the terminal, using command like this:
`/Applications/Subl.app/Contents/MacOS/applet subl://open?url=file:///Users/username/version-control/symfony/hello_world/src/AppBundle/Controller/DefaultController.php&line=157`
, it goes into background immediately.. So I can't see any output.

**Comment by dhoulb** [comment]
I'm not sure, sorry! If you look under **Security & Privacy** in your Mac preferences, it might be listed there as a blocked app (you can click to override it).
