### ISSUE TITLE
crash under Yosemite

### ISSUE THREAD

**Issue by masciugo** [dhoulb/subl#6]
Under Yosemite os x subl crash soon after I launch it. I could not collect any other evidence, sorry.

**Comment by Yoshyn** [comment]
:+1: 
Same thing, it seem to open sublime text (see the icon during 1 second in the dock) and the icon disappear.

**Comment by Yoshyn** [comment]
I fix my concern by adding a symlink of my local install with homebrew to /Application/Sublime Text.app.

I've try to use the path parameter with no success.

So I take few time to look the code :

```AppleScript
set subl_path to subl_path & "/Contents/SharedSupport/bin/subl"
```
I never done AppleScript what the purpose of the '&' operator. An concatenation operator? Why this step?

A cool feature will be to add an error if the subl_path is wrong. Something like:
```AppleScript
set subl_exec to (subl_path) & "file$"
try
    subl_exec as alias
    do shell script "\"" & subl_path & "\" \"" & subl_file & ":" & subl_line & "\""
on error
    display dialog "subl_path is wrong well set" & subl_path
end try
```

**Comment by cachrisman** [comment]
+1

I get the following in Console:

```
2/19/16 2:19:55.851 PM lsd[334]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
2/19/16 2:19:55.909 PM launchservicesd[84]: SecTaskLoadEntitlements failed error=22
2/19/16 2:19:55.915 PM launchservicesd[84]: SecTaskLoadEntitlements failed error=22
2/19/16 2:19:56.089 PM appleeventsd[54]: SecTaskLoadEntitlements failed error=22
```

**Comment by dhoulb** [comment]
Sorry guys, I don't have the necessary skillz to really figure this out. If anyone can get to the bottom of it, feel free to do a fork or pull request! Thanks.
