### ISSUE TITLE
Subl modifies global path

### ISSUE THREAD

**Issue by WaygoneWilco** [dhoulb/subl#9]
Installed Subl on Ubuntu 14.04.2 LTS
Using Firefox 37.0.1 

After installing Subl, the default path when opening a recent download from the Firefox toolbar opens Sublime Text to a blank file with the folder browser open to the location of the download.

Now did it while trying to open a folder from Archive Manager.

My mistake in setting up subl? Or a common thing?

**Comment by dhoulb** [comment]
Don't have any ideas for you I'm afraid! I'm surprised Subl works at all on Ubuntu — it's built in AppleScript for Macs, maybe that's why :\
